// @vitest-environment node
/**
 * The layer-2 fakes stay in layer 2 (#433 S9).
 *
 * `app/e2e/lib/fake-graph.ts` answers Microsoft Graph from synthetic fixtures,
 * and `app/e2e/lib/fake-converter.ts` answers the document converter. Either one
 * reachable from production would be a switch that points real tool calls at
 * canned data, or a real file at a fake that fabricates its text: the
 * production-configuration hole SD-12 and the app-path README refuse. They are
 * installed from the TEST side only (`app/e2e/lib/app.ts`), and this file is
 * the pin that production code never reaches them, or their fixtures.
 *
 * `e2e-not-in-ci.test.ts` already pins that nothing under `app/src/` imports
 * from `e2e/`. This widens that to the packages, which are production code too
 * (the Graph tools live in `@hames-ai/connectors`, the converter client in
 * `@hames-ai/harness-patterns`), and closes three ways round an import scan:
 * any string naming an `e2e/` path (a fixture read is not an import), a NAME
 * scan (a computed import has no `/e2e/` in its specifier), and the alias
 * tables (`package.json` `imports`/`exports`, `tsconfig.json` `paths`), through
 * which a specifier with no `e2e/` in it can still resolve into one.
 *
 * The second half pins that the fixtures stay synthetic. The repository is
 * public, so a fixture pasted from a real Graph response would publish a real
 * tenant. Every fixture, binary or not, is read as latin1, and every email
 * domain, URL host and bare host in it must be one of Microsoft's reserved
 * example names, `contoso` (the home tenancy) and `fabrikam` (outside it), or
 * the OOXML schema host. The binaries must also carry no author metadata, and
 * the `.docx` files must stay STORED, so this scan can read them at all. They
 * are generated by `app/e2e/lib/fixture-binaries.ts`.
 *
 * Layer 1, in CI. It reads the e2e tree as FILES and imports nothing from it.
 */
import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const APP = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const REPO = path.resolve(APP, '..')
const SELF = path
  .relative(REPO, fileURLToPath(import.meta.url))
  .split(path.sep)
  .join('/')

const FAKES = ['app/e2e/lib/fake-graph.ts', 'app/e2e/lib/fake-converter.ts']
const FIXTURES = path.join(APP, 'e2e/fixtures')
const read = (f: string, encoding: BufferEncoding = 'utf8') =>
  readFileSync(path.join(REPO, f), encoding)

/** Every file under `dir`, recursively, as repo-relative POSIX paths, skipping
 *  directories that are not source. */
function walk(dir: string, skip: (name: string) => boolean): string[] {
  const out: string[] = []
  for (const entry of readdirSync(dir)) {
    if (skip(entry)) continue
    const full = path.join(dir, entry)
    if (statSync(full).isDirectory()) out.push(...walk(full, skip))
    else out.push(path.relative(REPO, full).split(path.sep).join('/'))
  }
  return out
}

const NOT_SOURCE = new Set(['node_modules', '__tests__', 'baml_client', 'dist', 'coverage'])
const PACKAGES = readdirSync(path.join(REPO, 'packages')).filter((p) =>
  statSync(path.join(REPO, 'packages', p)).isDirectory(),
)

/** Production source: `app/src`, every package, and the app's build config,
 *  without tests or generated code. */
const PRODUCTION = [
  ...walk(path.join(APP, 'src'), (n) => NOT_SOURCE.has(n)),
  ...PACKAGES.flatMap((p) => walk(path.join(REPO, 'packages', p), (n) => NOT_SOURCE.has(n))),
  'app/app.config.ts',
].filter((f) => /\.(ts|tsx|js|mjs|cjs)$/.test(f) && !/\.(test|spec)\.(ts|tsx)$/.test(f))

/** `text` with its comments removed. String literals are matched first, so a
 *  `//` inside one (a URL) is kept rather than read as a comment. */
function stripComments(text: string): string {
  return text.replace(
    /("(?:\\.|[^"\\\n])*"|'(?:\\.|[^'\\\n])*'|`(?:\\[\s\S]|[^`\\])*`)|\/\*[\s\S]*?\*\/|\/\/[^\n]*/g,
    (_match, literal: string | undefined) => literal ?? '',
  )
}

/** Every string leaf of a JSON value: the targets of an alias table. */
function targets(value: unknown): string[] {
  if (typeof value === 'string') return [value]
  if (value && typeof value === 'object') return Object.values(value).flatMap(targets)
  return []
}

describe('production code never reaches the layer-2 fakes', () => {
  // Guards against a vacuous pass: a fake moved or renamed would leave every
  // scan below green while protecting nothing.
  it('the fakes exist where this pin looks, and there is production code to scan', () => {
    for (const fake of FAKES) expect(existsSync(path.join(REPO, fake)), fake).toBe(true)
    expect(PRODUCTION.length).toBeGreaterThan(200)
    expect(PRODUCTION).toContain('app/src/lib/app-tools/index.server.ts')
    expect(PRODUCTION).toContain('app/app.config.ts')
    expect(PRODUCTION).toContain('packages/connectors/graph/graph-tools.server.ts')
    expect(PRODUCTION).toContain('packages/harness-patterns/stash/doc-convert.server.ts')
  })

  it('no production string names an e2e/ path, import or not', () => {
    const offenders = PRODUCTION.flatMap((f) =>
      (stripComments(read(f)).match(/['"`][^'"`\n]*\be2e\//g) ?? []).map((m) => `${f}: ${m}`),
    )
    expect(offenders).toEqual([])
  })

  it('no production module names a fake, so not even a computed import reaches one', () => {
    const names = FAKES.map((f) => path.basename(f, '.ts'))
    const offenders = PRODUCTION.filter((f) => f !== SELF).flatMap((f) => {
      const text = read(f)
      return names.filter((n) => text.includes(n)).map((n) => `${f} names ${n}`)
    })
    expect(offenders).toEqual([])
  })

  it('no package alias and no tsconfig path resolves into e2e/', () => {
    const manifests = ['app/package.json', ...PACKAGES.map((p) => `packages/${p}/package.json`)]
      .filter((f) => existsSync(path.join(REPO, f)))
      .map((f) => ({ f, pkg: JSON.parse(read(f)) as { imports?: unknown; exports?: unknown } }))
    const aliases = manifests.flatMap(({ f, pkg }) =>
      [...targets(pkg.imports), ...targets(pkg.exports)].map((t) => ({ f, t })),
    )
    const tsconfig = JSON.parse(read('app/tsconfig.json')) as {
      compilerOptions?: { paths?: unknown }
    }
    const paths = targets(tsconfig.compilerOptions?.paths).map((t) => ({
      f: 'app/tsconfig.json',
      t,
    }))
    // Not vacuous: the packages export entry points, and the app maps `~/*`.
    expect(manifests.length).toBeGreaterThan(5)
    expect(aliases.length).toBeGreaterThan(5)
    expect(paths.length).toBeGreaterThan(0)

    const offenders = [...aliases, ...paths]
      .filter(({ t }) => /\be2e\//.test(t))
      .map(({ f, t }) => `${f}: ${t}`)
    expect(offenders).toEqual([])
  })
})

describe('the layer-2 fixtures are synthetic', () => {
  const FILES = walk(FIXTURES, () => false)
  /** Every fixture as latin1, so a binary is scanned byte for byte. */
  const latin1 = (f: string) => read(f, 'latin1')

  /** `contoso.com` and `fabrikam.com`, or a subdomain of either. */
  const EMAIL_DOMAIN = /^(?:[a-z0-9-]+\.)*(?:contoso|fabrikam)\.com$/
  /** The same, plus the tenants' SharePoint and OneDrive hosts, and the OOXML
   *  schema host every `.docx` names in its namespaces. */
  const allowedHost = (host: string) =>
    /^(?:(?:[a-z0-9-]+\.)*(?:contoso|fabrikam)\.com|(?:contoso|fabrikam)(?:-my)?\.sharepoint\.com)$/.test(
      host,
    ) || host === 'schemas.openxmlformats.org'
  /** A token a host pattern also matches that is a file name, not a host. */
  const FILE_NAME = /\.(docx|pdf|txt|loop|md|json|xml|rels)$/

  it('there are fixtures to check, binaries included, and the scans find something in them', () => {
    expect(FILES.filter((f) => /\.(json|txt)$/.test(f)).length).toBeGreaterThan(4)
    expect(FILES.filter((f) => /\.(docx|pdf)$/.test(f)).length).toBeGreaterThan(2)
    const all = FILES.map(latin1).join('\n')
    expect(all.match(/[\w.+-]+@[\w-]+(?:\.[\w-]+)+/g)?.length ?? 0).toBeGreaterThan(10)
    expect(all.match(/https?:\/\/[^/\s"]+/g)?.length ?? 0).toBeGreaterThan(5)
  })

  it('every email domain is contoso or fabrikam', () => {
    const offenders = FILES.flatMap((f) =>
      [...latin1(f).matchAll(/[\w.+-]+@([\w-]+(?:\.[\w-]+)+)/g)]
        .map((m) => m[1].toLowerCase())
        .filter((domain) => !EMAIL_DOMAIN.test(domain))
        .map((domain) => `${f}: ${domain}`),
    )
    expect(offenders).toEqual([])
  })

  it('every URL host is a contoso, fabrikam or OOXML schema host', () => {
    const offenders = FILES.flatMap((f) =>
      [...latin1(f).matchAll(/https?:\/\/([^/\s"?#:]+)/g)]
        .map((m) => m[1].toLowerCase())
        .filter((host) => !allowedHost(host))
        .map((host) => `${f}: ${host}`),
    )
    expect(offenders).toEqual([])
  })

  it('every bare host is one too: a site id, a quoted domain, an address', () => {
    const offenders = FILES.flatMap((f) =>
      [...latin1(f).matchAll(/(?:\/\/|"|@)((?:[a-z0-9-]+\.)+[a-z]{2,63})(?=[,/":?#\s)]|$)/gi)]
        .filter((m) => !m[0].startsWith('@odata.'))
        .map((m) => m[1].toLowerCase())
        .filter((host) => !FILE_NAME.test(host) && !allowedHost(host))
        .map((host) => `${f}: ${host}`),
    )
    expect(offenders).toEqual([])
  })

  it('no binary carries author metadata, and each .docx stays stored so it can be scanned', () => {
    const pdfs = FILES.filter((f) => f.endsWith('.pdf'))
    const docxs = FILES.filter((f) => f.endsWith('.docx'))
    expect(pdfs.length).toBeGreaterThan(0)
    expect(docxs.length).toBeGreaterThan(0)
    const offenders = [
      ...pdfs.flatMap((f) =>
        ['/Info', '/Author', '/Creator']
          .filter((k) => latin1(f).includes(k))
          .map((k) => `${f}: ${k}`),
      ),
      ...docxs.flatMap((f) =>
        ['docProps/', 'w:author', 'dc:creator']
          .filter((k) => latin1(f).includes(k))
          .map((k) => `${f}: ${k}`),
      ),
      ...docxs.filter((f) => !latin1(f).includes('<w:document')).map((f) => `${f}: not stored`),
    ]
    expect(offenders).toEqual([])
  })
})
