/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, BamlCtxManager, Image, Audio, Pdf, Video, FunctionLog } from
"@boundaryml/baml"
import { toBamlError, HTTPRequest, ClientRegistry } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type * as types from "./types"
import type {Attempt, ControllerAction, CriticResult, DescribeBatchResult, DescribeItemSummary, DescribeTarget, ExpandedRef, FewShot, LoopTurn, Message, PlanResult, PriorResult, ReferenceCandidate, ReferenceSelection, ReferenceSelectorResult, RouteOption, RoutingResult, ScreenVerdict, ToolCall, ToolCallRequest, ToolDescription, ToolResult} from "./types"
import type TypeBuilder from "./type_builder"
import type * as events from "./events"

type TickReason = "Unknown";

type BamlCallOptions<EventsT = never> = {
tb?: TypeBuilder
clientRegistry?: ClientRegistry
client?: string
env?: Record<string, string | undefined>
  onTick?: (reason: TickReason, log: FunctionLog | null) => void
  events?: EventsT
  }

  export class AsyncHttpRequest {
  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

  
  async ActorController(
  user_message: string,intent: string,tools: types.ToolDescription[],attempts: types.Attempt[],context?: string | null,few_shots?: types.FewShot[] | null,attempt_n?: number | null,max_attempts?: number | null,multi_call_mode?: string | null,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "ActorController",
      {
      "user_message": user_message,"intent": intent,"tools": tools,"attempts": attempts,"context": context?? null,"few_shots": few_shots?? null,"attempt_n": attempt_n?? null,"max_attempts": max_attempts?? null,"multi_call_mode": multi_call_mode?? null
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async CompactIntent(
  history: types.Message[],latest: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "CompactIntent",
      {
      "history": history,"latest": latest
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async Critic(
  intent: string,attempts: types.Attempt[],
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "Critic",
      {
      "intent": intent,"attempts": attempts
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async GenerateConversationTitle(
  user_message: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "GenerateConversationTitle",
      {
      "user_message": user_message
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async LoopController(
  user_message: string,intent: string,tools: types.ToolDescription[],turns: types.LoopTurn[],context?: string | null,turns_previous_runs?: types.PriorResult[] | null,few_shots?: types.FewShot[] | null,multi_call_mode?: string | null,plan_context?: string | null,return_style?: string | null,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "LoopController",
      {
      "user_message": user_message,"intent": intent,"tools": tools,"turns": turns,"context": context?? null,"turns_previous_runs": turns_previous_runs?? null,"few_shots": few_shots?? null,"multi_call_mode": multi_call_mode?? null,"plan_context": plan_context?? null,"return_style": return_style?? null
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async Planner(
  user_message: string,intent: string,tools: types.ToolDescription[],context?: string | null,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "Planner",
      {
      "user_message": user_message,"intent": intent,"tools": tools,"context": context?? null
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async ReferenceSelector(
  intent: string,recent_messages: types.Message[],candidates: types.ReferenceCandidate[],
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "ReferenceSelector",
      {
      "intent": intent,"recent_messages": recent_messages,"candidates": candidates
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async ResultDescribe(
  tool: string,tool_args: string,reasoning: string,result: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "ResultDescribe",
      {
      "tool": tool,"tool_args": tool_args,"reasoning": reasoning,"result": result
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async ResultDescribeBatch(
  items: types.DescribeTarget[],
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "ResultDescribeBatch",
      {
      "items": items
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async RetrieveQuery(
  history: types.Message[],latest: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "RetrieveQuery",
      {
      "history": history,"latest": latest
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async Router(
  message: string,routes: types.RouteOption[],history: types.Message[],
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "Router",
      {
      "message": message,"routes": routes,"history": history
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async ScreenUntrustedContent(
  source: string,content: string,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "ScreenUntrustedContent",
      {
      "source": source,"content": content
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
  async Synthesize(
  user_message: string,intent: string,turns: types.LoopTurn[],has_error: boolean,error_message?: string | null,
  __baml_options__?: BamlCallOptions<never>
  ): Promise<HTTPRequest> {
    try {
    const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
    const __env__: Record<string, string> = Object.fromEntries(
      Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __baml_options__?.clientRegistry;
      if (__baml_options__?.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__baml_options__.client);
      }

      return await this.runtime.buildRequest(
      "Synthesize",
      {
      "user_message": user_message,"intent": intent,"turns": turns,"has_error": has_error,"error_message": error_message?? null
      },
      this.ctxManager.cloneContext(),
      __baml_options__?.tb?.__tb(),
      __clientRegistry__,
      false,
      __env__
      )
      } catch (error) {
      throw toBamlError(error);
      }
      }
      
      }

      export class AsyncHttpStreamRequest {
      constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager) {}

      
      async ActorController(
      user_message: string,intent: string,tools: types.ToolDescription[],attempts: types.Attempt[],context?: string | null,few_shots?: types.FewShot[] | null,attempt_n?: number | null,max_attempts?: number | null,multi_call_mode?: string | null,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "ActorController",
          {
          "user_message": user_message,"intent": intent,"tools": tools,"attempts": attempts,"context": context?? null,"few_shots": few_shots?? null,"attempt_n": attempt_n?? null,"max_attempts": max_attempts?? null,"multi_call_mode": multi_call_mode?? null
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async CompactIntent(
      history: types.Message[],latest: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "CompactIntent",
          {
          "history": history,"latest": latest
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async Critic(
      intent: string,attempts: types.Attempt[],
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "Critic",
          {
          "intent": intent,"attempts": attempts
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async GenerateConversationTitle(
      user_message: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "GenerateConversationTitle",
          {
          "user_message": user_message
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async LoopController(
      user_message: string,intent: string,tools: types.ToolDescription[],turns: types.LoopTurn[],context?: string | null,turns_previous_runs?: types.PriorResult[] | null,few_shots?: types.FewShot[] | null,multi_call_mode?: string | null,plan_context?: string | null,return_style?: string | null,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "LoopController",
          {
          "user_message": user_message,"intent": intent,"tools": tools,"turns": turns,"context": context?? null,"turns_previous_runs": turns_previous_runs?? null,"few_shots": few_shots?? null,"multi_call_mode": multi_call_mode?? null,"plan_context": plan_context?? null,"return_style": return_style?? null
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async Planner(
      user_message: string,intent: string,tools: types.ToolDescription[],context?: string | null,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "Planner",
          {
          "user_message": user_message,"intent": intent,"tools": tools,"context": context?? null
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async ReferenceSelector(
      intent: string,recent_messages: types.Message[],candidates: types.ReferenceCandidate[],
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "ReferenceSelector",
          {
          "intent": intent,"recent_messages": recent_messages,"candidates": candidates
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async ResultDescribe(
      tool: string,tool_args: string,reasoning: string,result: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "ResultDescribe",
          {
          "tool": tool,"tool_args": tool_args,"reasoning": reasoning,"result": result
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async ResultDescribeBatch(
      items: types.DescribeTarget[],
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "ResultDescribeBatch",
          {
          "items": items
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async RetrieveQuery(
      history: types.Message[],latest: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "RetrieveQuery",
          {
          "history": history,"latest": latest
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async Router(
      message: string,routes: types.RouteOption[],history: types.Message[],
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "Router",
          {
          "message": message,"routes": routes,"history": history
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async ScreenUntrustedContent(
      source: string,content: string,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "ScreenUntrustedContent",
          {
          "source": source,"content": content
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
      async Synthesize(
      user_message: string,intent: string,turns: types.LoopTurn[],has_error: boolean,error_message?: string | null,
      __baml_options__?: BamlCallOptions<never>
      ): Promise<HTTPRequest> {
        try {
        const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
        const __env__: Record<string, string> = Object.fromEntries(
          Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
          );

          // Resolve client option to clientRegistry (client takes precedence)
          let __clientRegistry__ = __baml_options__?.clientRegistry;
          if (__baml_options__?.client) {
            __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
            __clientRegistry__.setPrimary(__baml_options__.client);
          }

          return await this.runtime.buildRequest(
          "Synthesize",
          {
          "user_message": user_message,"intent": intent,"turns": turns,"has_error": has_error,"error_message": error_message?? null
          },
          this.ctxManager.cloneContext(),
          __baml_options__?.tb?.__tb(),
          __clientRegistry__,
          true,
          __env__
          )
          } catch (error) {
          throw toBamlError(error);
          }
          }
          
          }