/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, FunctionResult, BamlCtxManager, Image, Audio, Pdf, Video, FunctionLog,
HTTPRequest } from "@boundaryml/baml"
import { toBamlError, BamlStream, BamlAbortError, Collector, ClientRegistry } from "@boundaryml/baml"
import type { Checked, Check, RecursivePartialNull as MovedRecursivePartialNull } from "./types"
import type { partial_types } from "./partial_types"
import type * as types from "./types"
import type {Attempt, ControllerAction, CriticResult, DescribeBatchResult, DescribeItemSummary, DescribeTarget, ExpandedRef, FewShot, LoopTurn, Message, PlanResult, PriorResult, ReferenceCandidate, ReferenceSelection, ReferenceSelectorResult, RouteOption, RoutingResult, ScreenVerdict, ToolCall, ToolCallRequest, ToolDescription, ToolResult} from "./types"
import type TypeBuilder from "./type_builder"
import { AsyncHttpRequest, AsyncHttpStreamRequest } from "./async_request"
import { LlmResponseParser, LlmStreamParser } from "./parser"
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX,
DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"
import type * as events from "./events"

/**
* @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
*/
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>

    type TickReason = "Unknown";

    type BamlCallOptions<WatchersT = never> = {
    tb?: TypeBuilder
    clientRegistry?: ClientRegistry
    client?: string
    collector?: Collector | Collector[]
    env?: Record<string, string | undefined>
      tags?: Record<string, string>
        signal?: AbortSignal
        onTick?: (reason: TickReason, log: FunctionLog | null) => void
        watchers?: WatchersT
        }

        export class BamlAsyncClient {
        private runtime: BamlRuntime
        private ctxManager: BamlCtxManager
        private streamClient: BamlStreamClient
        private httpRequest: AsyncHttpRequest
        private httpStreamRequest: AsyncHttpStreamRequest
        private llmResponseParser: LlmResponseParser
        private llmStreamParser: LlmStreamParser
        private bamlOptions: BamlCallOptions

        constructor(runtime: BamlRuntime, ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
        this.runtime = runtime
        this.ctxManager = ctxManager
        this.streamClient = new BamlStreamClient(runtime, ctxManager, bamlOptions)
        this.httpRequest = new AsyncHttpRequest(runtime, ctxManager)
        this.httpStreamRequest = new AsyncHttpStreamRequest(runtime, ctxManager)
        this.llmResponseParser = new LlmResponseParser(runtime, ctxManager)
        this.llmStreamParser = new LlmStreamParser(runtime, ctxManager)
        this.bamlOptions = bamlOptions || {}
        }

        withOptions(bamlOptions: BamlCallOptions) {
        return new BamlAsyncClient(this.runtime, this.ctxManager, bamlOptions)
        }

        get stream() {
        return this.streamClient
        }

        get request() {
        return this.httpRequest
        }

        get streamRequest() {
        return this.httpStreamRequest
        }

        get parse() {
        return this.llmResponseParser
        }

        get parseStream() {
        return this.llmStreamParser
        }

        
        async ActorController(
        user_message: string,intent: string,tools: types.ToolDescription[],attempts: types.Attempt[],context?: string | null,few_shots?: types.FewShot[] | null,attempt_n?: number | null,max_attempts?: number | null,multi_call_mode?: string | null,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.ControllerAction> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.ActorController(
          user_message,intent,tools,attempts,context,few_shots,attempt_n,max_attempts,multi_call_mode,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "ActorController",
            {
            "user_message": user_message,"intent": intent,"tools": tools,"attempts": attempts,"context": context?? null,"few_shots": few_shots?? null,"attempt_n": attempt_n?? null,"max_attempts": max_attempts?? null,"multi_call_mode": multi_call_mode?? null
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.ControllerAction
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async CompactIntent(
        history: types.Message[],latest: string,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<string> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.CompactIntent(
          history,latest,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "CompactIntent",
            {
            "history": history,"latest": latest
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as string
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async Critic(
        intent: string,attempts: types.Attempt[],
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.CriticResult> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.Critic(
          intent,attempts,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "Critic",
            {
            "intent": intent,"attempts": attempts
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.CriticResult
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async GenerateConversationTitle(
        user_message: string,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<string> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.GenerateConversationTitle(
          user_message,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "GenerateConversationTitle",
            {
            "user_message": user_message
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as string
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async LoopController(
        user_message: string,intent: string,tools: types.ToolDescription[],turns: types.LoopTurn[],context?: string | null,turns_previous_runs?: types.PriorResult[] | null,few_shots?: types.FewShot[] | null,multi_call_mode?: string | null,plan_context?: string | null,return_style?: string | null,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.ControllerAction> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.LoopController(
          user_message,intent,tools,turns,context,turns_previous_runs,few_shots,multi_call_mode,plan_context,return_style,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "LoopController",
            {
            "user_message": user_message,"intent": intent,"tools": tools,"turns": turns,"context": context?? null,"turns_previous_runs": turns_previous_runs?? null,"few_shots": few_shots?? null,"multi_call_mode": multi_call_mode?? null,"plan_context": plan_context?? null,"return_style": return_style?? null
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.ControllerAction
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async Planner(
        user_message: string,intent: string,tools: types.ToolDescription[],context?: string | null,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.PlanResult> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.Planner(
          user_message,intent,tools,context,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "Planner",
            {
            "user_message": user_message,"intent": intent,"tools": tools,"context": context?? null
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.PlanResult
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async ReferenceSelector(
        intent: string,recent_messages: types.Message[],candidates: types.ReferenceCandidate[],
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.ReferenceSelectorResult> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.ReferenceSelector(
          intent,recent_messages,candidates,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "ReferenceSelector",
            {
            "intent": intent,"recent_messages": recent_messages,"candidates": candidates
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.ReferenceSelectorResult
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async ResultDescribe(
        tool: string,tool_args: string,reasoning: string,result: string,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<string> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.ResultDescribe(
          tool,tool_args,reasoning,result,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "ResultDescribe",
            {
            "tool": tool,"tool_args": tool_args,"reasoning": reasoning,"result": result
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as string
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async ResultDescribeBatch(
        items: types.DescribeTarget[],
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.DescribeBatchResult> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.ResultDescribeBatch(
          items,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "ResultDescribeBatch",
            {
            "items": items
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.DescribeBatchResult
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async RetrieveQuery(
        history: types.Message[],latest: string,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<string> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.RetrieveQuery(
          history,latest,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "RetrieveQuery",
            {
            "history": history,"latest": latest
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as string
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async Router(
        message: string,routes: types.RouteOption[],history: types.Message[],
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.RoutingResult> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.Router(
          message,routes,history,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "Router",
            {
            "message": message,"routes": routes,"history": history
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.RoutingResult
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async ScreenUntrustedContent(
        source: string,content: string,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<types.ScreenVerdict> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.ScreenUntrustedContent(
          source,content,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "ScreenUntrustedContent",
            {
            "source": source,"content": content
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as types.ScreenVerdict
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
        async Synthesize(
        user_message: string,intent: string,turns: types.LoopTurn[],has_error: boolean,error_message?: string | null,
        __baml_options__?: BamlCallOptions<never>
        ): Promise<string> {
          try {
          const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
          const __signal__ = __options__.signal;

          if (__signal__?.aborted) {
          throw new BamlAbortError('Operation was aborted', __signal__.reason);
          }

          // Check if onTick is provided - route through streaming if so
          if (__options__.onTick) {
          const __stream__ = this.stream.Synthesize(
          user_message,intent,turns,has_error,error_message,
          __baml_options__
          );

          return await __stream__.getFinalResponse();
          }

          const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
          [__options__.collector]) : [];
          const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
          const __env__: Record<string, string> = Object.fromEntries(
            Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
            );

            // Resolve client option to clientRegistry (client takes precedence)
            let __clientRegistry__ = __options__.clientRegistry;
            if (__options__.client) {
              __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
              __clientRegistry__.setPrimary(__options__.client);
            }

            const __raw__ = await this.runtime.callFunction(
            "Synthesize",
            {
            "user_message": user_message,"intent": intent,"turns": turns,"has_error": has_error,"error_message": error_message?? null
            },
            this.ctxManager.cloneContext(),
            __options__.tb?.__tb(),
            __clientRegistry__,
            __collector__,
            __options__.tags || {},
            __env__,
            __signal__,
            __options__.watchers,
            )
            return __raw__.parsed(false) as string
            } catch (error) {
            throw toBamlError(error);
            }
            }
            
            }

            class BamlStreamClient {
            private runtime: BamlRuntime
            private ctxManager: BamlCtxManager
            private bamlOptions: BamlCallOptions

            constructor(runtime: BamlRuntime, ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
            this.runtime = runtime
            this.ctxManager = ctxManager
            this.bamlOptions = bamlOptions || {}
            }

            
            ActorController(
            user_message: string,intent: string,tools: types.ToolDescription[],attempts: types.Attempt[],context?: string | null,few_shots?: types.FewShot[] | null,attempt_n?: number | null,max_attempts?: number | null,multi_call_mode?: string | null,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.ControllerAction, types.ControllerAction>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for ActorController", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "ActorController",
                {
                "user_message": user_message,"intent": intent,"tools": tools,"attempts": attempts,"context": context ?? null,"few_shots": few_shots ?? null,"attempt_n": attempt_n ?? null,"max_attempts": max_attempts ?? null,"multi_call_mode": multi_call_mode ?? null
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.ControllerAction, types.ControllerAction>(
                  __raw__,
                  (a): partial_types.ControllerAction => a,
                  (a): types.ControllerAction => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            CompactIntent(
            history: types.Message[],latest: string,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<string, string>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for CompactIntent", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "CompactIntent",
                {
                "history": history,"latest": latest
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<string, string>(
                  __raw__,
                  (a): string => a,
                  (a): string => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            Critic(
            intent: string,attempts: types.Attempt[],
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.CriticResult, types.CriticResult>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for Critic", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "Critic",
                {
                "intent": intent,"attempts": attempts
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.CriticResult, types.CriticResult>(
                  __raw__,
                  (a): partial_types.CriticResult => a,
                  (a): types.CriticResult => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            GenerateConversationTitle(
            user_message: string,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<string, string>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for GenerateConversationTitle", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "GenerateConversationTitle",
                {
                "user_message": user_message
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<string, string>(
                  __raw__,
                  (a): string => a,
                  (a): string => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            LoopController(
            user_message: string,intent: string,tools: types.ToolDescription[],turns: types.LoopTurn[],context?: string | null,turns_previous_runs?: types.PriorResult[] | null,few_shots?: types.FewShot[] | null,multi_call_mode?: string | null,plan_context?: string | null,return_style?: string | null,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.ControllerAction, types.ControllerAction>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for LoopController", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "LoopController",
                {
                "user_message": user_message,"intent": intent,"tools": tools,"turns": turns,"context": context ?? null,"turns_previous_runs": turns_previous_runs ?? null,"few_shots": few_shots ?? null,"multi_call_mode": multi_call_mode ?? null,"plan_context": plan_context ?? null,"return_style": return_style ?? null
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.ControllerAction, types.ControllerAction>(
                  __raw__,
                  (a): partial_types.ControllerAction => a,
                  (a): types.ControllerAction => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            Planner(
            user_message: string,intent: string,tools: types.ToolDescription[],context?: string | null,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.PlanResult, types.PlanResult>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for Planner", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "Planner",
                {
                "user_message": user_message,"intent": intent,"tools": tools,"context": context ?? null
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.PlanResult, types.PlanResult>(
                  __raw__,
                  (a): partial_types.PlanResult => a,
                  (a): types.PlanResult => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            ReferenceSelector(
            intent: string,recent_messages: types.Message[],candidates: types.ReferenceCandidate[],
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.ReferenceSelectorResult, types.ReferenceSelectorResult>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for ReferenceSelector", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "ReferenceSelector",
                {
                "intent": intent,"recent_messages": recent_messages,"candidates": candidates
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.ReferenceSelectorResult, types.ReferenceSelectorResult>(
                  __raw__,
                  (a): partial_types.ReferenceSelectorResult => a,
                  (a): types.ReferenceSelectorResult => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            ResultDescribe(
            tool: string,tool_args: string,reasoning: string,result: string,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<string, string>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for ResultDescribe", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "ResultDescribe",
                {
                "tool": tool,"tool_args": tool_args,"reasoning": reasoning,"result": result
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<string, string>(
                  __raw__,
                  (a): string => a,
                  (a): string => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            ResultDescribeBatch(
            items: types.DescribeTarget[],
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.DescribeBatchResult, types.DescribeBatchResult>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for ResultDescribeBatch", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "ResultDescribeBatch",
                {
                "items": items
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.DescribeBatchResult, types.DescribeBatchResult>(
                  __raw__,
                  (a): partial_types.DescribeBatchResult => a,
                  (a): types.DescribeBatchResult => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            RetrieveQuery(
            history: types.Message[],latest: string,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<string, string>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for RetrieveQuery", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "RetrieveQuery",
                {
                "history": history,"latest": latest
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<string, string>(
                  __raw__,
                  (a): string => a,
                  (a): string => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            Router(
            message: string,routes: types.RouteOption[],history: types.Message[],
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.RoutingResult, types.RoutingResult>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for Router", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "Router",
                {
                "message": message,"routes": routes,"history": history
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.RoutingResult, types.RoutingResult>(
                  __raw__,
                  (a): partial_types.RoutingResult => a,
                  (a): types.RoutingResult => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            ScreenUntrustedContent(
            source: string,content: string,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<partial_types.ScreenVerdict, types.ScreenVerdict>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for ScreenUntrustedContent", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "ScreenUntrustedContent",
                {
                "source": source,"content": content
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<partial_types.ScreenVerdict, types.ScreenVerdict>(
                  __raw__,
                  (a): partial_types.ScreenVerdict => a,
                  (a): types.ScreenVerdict => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
            Synthesize(
            user_message: string,intent: string,turns: types.LoopTurn[],has_error: boolean,error_message?: string | null,
            __baml_options__?: BamlCallOptions<never>
            ): BamlStream<string, string>
              {
              try {
              const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
              const __signal__ = __options__.signal;

              if (__signal__?.aborted) {
              throw new BamlAbortError('Operation was aborted', __signal__.reason);
              }

              let __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector :
              [__options__.collector]) : [];

              let __onTickWrapper__: (() => void) | undefined;

              // Create collector and wrap onTick if provided
              if (__options__.onTick) {
              const __tickCollector__ = new Collector("on-tick-collector");
              __collector__ = [...__collector__, __tickCollector__];

              __onTickWrapper__ = () => {
              const __log__ = __tickCollector__.last;
              if (__log__) {
              try {
              __options__.onTick!("Unknown", __log__);
              } catch (error) {
              console.error("Error in onTick callback for Synthesize", error);
              }
              }
              };
              }

              const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
              const __env__: Record<string, string> = Object.fromEntries(
                Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
                );

                // Resolve client option to clientRegistry (client takes precedence)
                let __clientRegistry__ = __options__.clientRegistry;
                if (__options__.client) {
                  __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
                  __clientRegistry__.setPrimary(__options__.client);
                }

                const __raw__ = this.runtime.streamFunction(
                "Synthesize",
                {
                "user_message": user_message,"intent": intent,"turns": turns,"has_error": has_error,"error_message": error_message ?? null
                },
                undefined,
                this.ctxManager.cloneContext(),
                __options__.tb?.__tb(),
                __clientRegistry__,
                __collector__,
                __options__.tags || {},
                __env__,
                __signal__,
                __onTickWrapper__,
                )
                return new BamlStream<string, string>(
                  __raw__,
                  (a): string => a,
                  (a): string => a,
                  this.ctxManager.cloneContext(),
                  __options__.signal,
                  )
                  } catch (error) {
                  throw toBamlError(error);
                  }
                  }
                  
                  }

                  export const b = new BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME,
                  DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)