/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
import type { Checked, Check } from "./types"
import type {  Attempt,  ControllerAction,  CriticResult,  DescribeBatchResult,  DescribeItemSummary,  DescribeTarget,  ExpandedRef,  FewShot,  LoopTurn,  Message,  PlanResult,  PriorResult,  ReferenceCandidate,  ReferenceSelection,  ReferenceSelectorResult,  RouteOption,  RoutingResult,  ScreenVerdict,  ToolCall,  ToolCallRequest,  ToolDescription,  ToolResult } from "./types"
import type * as types from "./types"

/******************************************************************************
*
*  These types are used for streaming, for when an instance of a type
*  is still being built up and any of its fields is not yet fully available.
*
******************************************************************************/

export interface StreamState<T> {
  value: T
  state: "Pending" | "Incomplete" | "Complete"
}

export namespace partial_types {
    /**
     * A previous attempt for actor-critic retry loop
    */
    export interface Attempt {
      n?: number | null
      action?: ControllerAction | null
      result?: string | null
      error?: string | null
      feedback?: string | null
    }
    /**
     * Action decision returned by loop and actor controllers
    */
    export interface ControllerAction {
      reasoning?: string | null
      tool_name?: string | null
      tool_args?: string | null
      additional_calls?: ToolCallRequest[] | null
      status?: string | null
      is_final?: boolean | null
    }
    /**
     * Critic evaluation result
    */
    export interface CriticResult {
      is_sufficient?: boolean | null
      explanation?: string | null
      suggested_approach?: string | null
    }
    export interface DescribeBatchResult {
      summaries: DescribeItemSummary[]
    }
    export interface DescribeItemSummary {
      id?: string | null
      summary?: string | null
    }
    export interface DescribeTarget {
      id?: string | null
      tool?: string | null
      tool_args?: string | null
      reasoning?: string | null
      result?: string | null
    }
    /**
     * A ref:<id> argument that was expanded inline during a turn
    */
    export interface ExpandedRef {
      ref_id?: string | null
      content?: string | null
    }
    /**
     * A canonical example of how the agent should pick a tool for a given user request.
 * Few-shots are domain-specific — pass at config time on a per-route basis (e.g., a
 * neo4j route ships graph-query examples; a web route ships search-formulation examples).
    */
    export interface FewShot {
      user?: string | null
      reasoning?: string | null
      tool?: string | null
      args?: string | null
    }
    /**
     * A single turn in a loop-based pattern
    */
    export interface LoopTurn {
      n?: number | null
      reasoning?: string | null
      status?: string | null
      tool_call?: ToolCall | null
      additional_calls?: ToolCallRequest[] | null
      tool_result?: ToolResult | null
      expansions?: ExpandedRef[] | null
    }
    /**
     * Conversation message for history context
    */
    export interface Message {
      role?: string | null
      content?: string | null
    }
    /**
     * Strategic plan produced by the `planner` pattern BEFORE any tool runs.
 * The planner never executes a tool — it only describes the approach, which
 * downstream loop patterns receive as their trailing `planContext` argument
 * (harness-patterns/patterns/planner.server.ts → `formatPlanContext`).
 * `LoopController` takes it as its own `plan_context` parameter (tier 2);
 * `ActorController` merges it into `context`, which is cache-safe there.
    */
    export interface PlanResult {
      /**
       * Field name deliberately matches ControllerAction.reasoning — one
       * vocabulary for "why this course of action", wherever it is produced.
       */
      reasoning?: string | null
      plan?: string | null
      n_steps?: number | null
    }
    /**
     * A compact reference to a tool result from a previous task/turn.
 * The LLM can pass ref:<ref_id> as a tool argument value to retrieve full data.
    */
    export interface PriorResult {
      ref_id?: string | null
      tool?: string | null
      summary?: string | null
      expanded_in_turn?: number | null
    }
    export interface ReferenceCandidate {
      ref_id?: string | null
      tool?: string | null
      summary?: string | null
      tool_args?: string | null
      ts_offset_s?: number | null
    }
    export interface ReferenceSelection {
      ref_id?: string | null
      reason?: string | null
    }
    export interface ReferenceSelectorResult {
      reasoning?: string | null
      selected: ReferenceSelection[]
    }
    /**
     * A named route option for the router pattern
    */
    export interface RouteOption {
      name?: string | null
      description?: string | null
    }
    /**
     * Routing decision
    */
    export interface RoutingResult {
      intent?: string | null
      needs_tool?: boolean | null
      route?: string | null
      response?: string | null
    }
    export interface ScreenVerdict {
      injection_detected?: boolean | null
      reason?: string | null
      spans: string[]
    }
    /**
     * Tool call event
    */
    export interface ToolCall {
      tool?: string | null
      args?: string | null
    }
    /**
     * One extra tool call inside a multi-call turn (ControllerAction.additional_calls).
 * Field names deliberately match ControllerAction's singular fields — one
 * vocabulary, demonstrated everywhere (see the few-shot encoding lesson in
 * simpleLoop.baml: disagreeing demonstrations are defects).
    */
    export interface ToolCallRequest {
      tool_name?: string | null
      tool_args?: string | null
    }
    /**
     * Description of an available tool, passed to patterns at runtime
    */
    export interface ToolDescription {
      name?: string | null
      description?: string | null
      args_schema?: string | null
    }
    /**
     * Tool execution result
    */
    export interface ToolResult {
      tool?: string | null
      result?: string | null
      success?: boolean | null
      error?: string | null
    }
}