/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { BamlRuntime, FunctionResult, BamlCtxManager, Image, Audio, Pdf, Video, Collector, FunctionLog } from "@boundaryml/baml"
import { toBamlError, BamlAbortError, ClientRegistry, type HTTPRequest } from "@boundaryml/baml"
import type { Checked, Check, RecursivePartialNull as MovedRecursivePartialNull } from "./types"
import type * as types from "./types"
import type {Attempt, ControllerAction, CriticResult, DescribeBatchResult, DescribeItemSummary, DescribeTarget, ExpandedRef, FewShot, LoopTurn, Message, PlanResult, PriorResult, ReferenceCandidate, ReferenceSelection, ReferenceSelectorResult, RouteOption, RoutingResult, ScreenVerdict, ToolCall, ToolCallRequest, ToolDescription, ToolResult} from "./types"
import type TypeBuilder from "./type_builder"
import { HttpRequest, HttpStreamRequest } from "./sync_request"
import { LlmResponseParser, LlmStreamParser } from "./parser"
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"
import type * as events from "./events"

/**
 * @deprecated Use RecursivePartialNull from 'baml_client/types' instead.
 * Example:
 * ```ts
 * import { RecursivePartialNull } from './baml_client/types'
 * ```
 */
export type RecursivePartialNull<T> = MovedRecursivePartialNull<T>;

type TickReason = "Unknown";

type BamlCallOptions<WatchersT = never> = {
  tb?: TypeBuilder
  clientRegistry?: ClientRegistry
  client?: string
  collector?: Collector | Collector[]
  env?: Record<string, string | undefined>
  tags?: Record<string, string>
  signal?: AbortSignal
  onTick?: (reason: TickReason, log: FunctionLog | null) => void
  watchers?: WatchersT
}

export class BamlSyncClient {
  private httpRequest: HttpRequest
  private httpStreamRequest: HttpStreamRequest
  private llmResponseParser: LlmResponseParser
  private llmStreamParser: LlmStreamParser
  private bamlOptions: BamlCallOptions

  constructor(private runtime: BamlRuntime, private ctxManager: BamlCtxManager, bamlOptions?: BamlCallOptions) {
    this.httpRequest = new HttpRequest(runtime, ctxManager)
    this.httpStreamRequest = new HttpStreamRequest(runtime, ctxManager)
    this.llmResponseParser = new LlmResponseParser(runtime, ctxManager)
    this.llmStreamParser = new LlmStreamParser(runtime, ctxManager)
    this.bamlOptions = bamlOptions || {}
  }

  withOptions(bamlOptions: BamlCallOptions) {
    return new BamlSyncClient(this.runtime, this.ctxManager, bamlOptions)
  }

  /*
  * @deprecated NOT IMPLEMENTED as streaming must by async. We
  * are not providing an async version as we want to reserve the
  * right to provide a sync version in the future.
  */
  get stream() {
    throw new Error("stream is not available in BamlSyncClient. Use `import { b } from 'baml_client/async_client")
  }

  get request() {
    return this.httpRequest
  }

  get streamRequest() {
    return this.httpStreamRequest
  }

  get parse() {
    return this.llmResponseParser
  }

  get parseStream() {
    return this.llmStreamParser
  }

  
  ActorController(
      user_message: string,intent: string,tools: types.ToolDescription[],attempts: types.Attempt[],context?: string | null,few_shots?: types.FewShot[] | null,attempt_n?: number | null,max_attempts?: number | null,multi_call_mode?: string | null,
      __baml_options__?: BamlCallOptions<never>
  ): types.ControllerAction {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "ActorController",
        {
          "user_message": user_message,"intent": intent,"tools": tools,"attempts": attempts,"context": context?? null,"few_shots": few_shots?? null,"attempt_n": attempt_n?? null,"max_attempts": max_attempts?? null,"multi_call_mode": multi_call_mode?? null
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ControllerAction
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  CompactIntent(
      history: types.Message[],latest: string,
      __baml_options__?: BamlCallOptions<never>
  ): string {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "CompactIntent",
        {
          "history": history,"latest": latest
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as string
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  Critic(
      intent: string,attempts: types.Attempt[],
      __baml_options__?: BamlCallOptions<never>
  ): types.CriticResult {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "Critic",
        {
          "intent": intent,"attempts": attempts
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.CriticResult
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  GenerateConversationTitle(
      user_message: string,
      __baml_options__?: BamlCallOptions<never>
  ): string {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "GenerateConversationTitle",
        {
          "user_message": user_message
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as string
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  LoopController(
      user_message: string,intent: string,tools: types.ToolDescription[],turns: types.LoopTurn[],context?: string | null,turns_previous_runs?: types.PriorResult[] | null,few_shots?: types.FewShot[] | null,multi_call_mode?: string | null,plan_context?: string | null,return_style?: string | null,
      __baml_options__?: BamlCallOptions<never>
  ): types.ControllerAction {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "LoopController",
        {
          "user_message": user_message,"intent": intent,"tools": tools,"turns": turns,"context": context?? null,"turns_previous_runs": turns_previous_runs?? null,"few_shots": few_shots?? null,"multi_call_mode": multi_call_mode?? null,"plan_context": plan_context?? null,"return_style": return_style?? null
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ControllerAction
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  Planner(
      user_message: string,intent: string,tools: types.ToolDescription[],context?: string | null,
      __baml_options__?: BamlCallOptions<never>
  ): types.PlanResult {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "Planner",
        {
          "user_message": user_message,"intent": intent,"tools": tools,"context": context?? null
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.PlanResult
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  ReferenceSelector(
      intent: string,recent_messages: types.Message[],candidates: types.ReferenceCandidate[],
      __baml_options__?: BamlCallOptions<never>
  ): types.ReferenceSelectorResult {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "ReferenceSelector",
        {
          "intent": intent,"recent_messages": recent_messages,"candidates": candidates
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ReferenceSelectorResult
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  ResultDescribe(
      tool: string,tool_args: string,reasoning: string,result: string,
      __baml_options__?: BamlCallOptions<never>
  ): string {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "ResultDescribe",
        {
          "tool": tool,"tool_args": tool_args,"reasoning": reasoning,"result": result
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as string
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  ResultDescribeBatch(
      items: types.DescribeTarget[],
      __baml_options__?: BamlCallOptions<never>
  ): types.DescribeBatchResult {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "ResultDescribeBatch",
        {
          "items": items
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.DescribeBatchResult
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  RetrieveQuery(
      history: types.Message[],latest: string,
      __baml_options__?: BamlCallOptions<never>
  ): string {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "RetrieveQuery",
        {
          "history": history,"latest": latest
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as string
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  Router(
      message: string,routes: types.RouteOption[],history: types.Message[],
      __baml_options__?: BamlCallOptions<never>
  ): types.RoutingResult {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "Router",
        {
          "message": message,"routes": routes,"history": history
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.RoutingResult
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  ScreenUntrustedContent(
      source: string,content: string,
      __baml_options__?: BamlCallOptions<never>
  ): types.ScreenVerdict {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "ScreenUntrustedContent",
        {
          "source": source,"content": content
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as types.ScreenVerdict
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
  Synthesize(
      user_message: string,intent: string,turns: types.LoopTurn[],has_error: boolean,error_message?: string | null,
      __baml_options__?: BamlCallOptions<never>
  ): string {
    try {
      const __options__ = { ...this.bamlOptions, ...(__baml_options__ || {}) }
      const __signal__ = __options__.signal;

      if (__signal__?.aborted) {
        throw new BamlAbortError('Operation was aborted', __signal__.reason);
      }

      // Check if onTick is provided and reject for sync operations
      if (__options__.onTick) {
        throw new Error("onTick is not supported for synchronous functions. Please use the async client instead.");
      }

      const __collector__ = __options__.collector ? (Array.isArray(__options__.collector) ? __options__.collector : [__options__.collector]) : [];
      const __rawEnv__ = __baml_options__?.env ? { ...process.env, ...__baml_options__.env } : { ...process.env };
      const __env__: Record<string, string> = Object.fromEntries(
        Object.entries(__rawEnv__).filter(([_, value]) => value !== undefined) as [string, string][]
      );

      // Resolve client option to clientRegistry (client takes precedence)
      let __clientRegistry__ = __options__.clientRegistry;
      if (__options__.client) {
        __clientRegistry__ = __clientRegistry__ || new ClientRegistry();
        __clientRegistry__.setPrimary(__options__.client);
      }

      const __raw__ = this.runtime.callFunctionSync(
        "Synthesize",
        {
          "user_message": user_message,"intent": intent,"turns": turns,"has_error": has_error,"error_message": error_message?? null
        },
        this.ctxManager.cloneContext(),
        __options__.tb?.__tb(),
        __clientRegistry__,
        __collector__,
        __options__.tags || {},
        __env__,
        __signal__,
        __options__.watchers,
      )
      return __raw__.parsed(false) as string
    } catch (error: any) {
      throw toBamlError(error);
    }
  }
  
}

export const b = new BamlSyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)