/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import { FieldType } from '@boundaryml/baml/native'
import { TypeBuilder as _TypeBuilder, EnumBuilder, EnumViewer, ClassBuilder, ClassViewer } from '@boundaryml/baml/type_builder'
import { DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME } from "./globals"

export { FieldType, EnumBuilder, ClassBuilder }

export default class TypeBuilder {
    private tb: _TypeBuilder;
    
    Attempt: ClassViewer<'Attempt', "n" | "action" | "result" | "error" | "feedback">;
    
    ControllerAction: ClassViewer<'ControllerAction', "reasoning" | "tool_name" | "tool_args" | "additional_calls" | "status" | "is_final">;
    
    CriticResult: ClassViewer<'CriticResult', "is_sufficient" | "explanation" | "suggested_approach">;
    
    DescribeBatchResult: ClassViewer<'DescribeBatchResult', "summaries">;
    
    DescribeItemSummary: ClassViewer<'DescribeItemSummary', "id" | "summary">;
    
    DescribeTarget: ClassViewer<'DescribeTarget', "id" | "tool" | "tool_args" | "reasoning" | "result">;
    
    ExpandedRef: ClassViewer<'ExpandedRef', "ref_id" | "content">;
    
    FewShot: ClassViewer<'FewShot', "user" | "reasoning" | "tool" | "args">;
    
    LoopTurn: ClassViewer<'LoopTurn', "n" | "reasoning" | "status" | "tool_call" | "additional_calls" | "tool_result" | "expansions">;
    
    Message: ClassViewer<'Message', "role" | "content">;
    
    PlanResult: ClassViewer<'PlanResult', "reasoning" | "plan" | "n_steps">;
    
    PriorResult: ClassViewer<'PriorResult', "ref_id" | "tool" | "summary" | "expanded_in_turn">;
    
    ReferenceCandidate: ClassViewer<'ReferenceCandidate', "ref_id" | "tool" | "summary" | "tool_args" | "ts_offset_s">;
    
    ReferenceSelection: ClassViewer<'ReferenceSelection', "ref_id" | "reason">;
    
    ReferenceSelectorResult: ClassViewer<'ReferenceSelectorResult', "reasoning" | "selected">;
    
    RouteOption: ClassViewer<'RouteOption', "name" | "description">;
    
    RoutingResult: ClassViewer<'RoutingResult', "intent" | "needs_tool" | "route" | "response">;
    
    ScreenVerdict: ClassViewer<'ScreenVerdict', "injection_detected" | "reason" | "spans">;
    
    ToolCall: ClassViewer<'ToolCall', "tool" | "args">;
    
    ToolCallRequest: ClassViewer<'ToolCallRequest', "tool_name" | "tool_args">;
    
    ToolDescription: ClassViewer<'ToolDescription', "name" | "description" | "args_schema">;
    
    ToolResult: ClassViewer<'ToolResult', "tool" | "result" | "success" | "error">;
    
    

    constructor() {
        this.tb = new _TypeBuilder({
          classes: new Set([
            "Attempt","ControllerAction","CriticResult","DescribeBatchResult","DescribeItemSummary","DescribeTarget","ExpandedRef","FewShot","LoopTurn","Message","PlanResult","PriorResult","ReferenceCandidate","ReferenceSelection","ReferenceSelectorResult","RouteOption","RoutingResult","ScreenVerdict","ToolCall","ToolCallRequest","ToolDescription","ToolResult",
          ]),
          enums: new Set([
            
          ]),
          runtime: DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME
        });
        
        this.Attempt = this.tb.classViewer("Attempt", [
          "n","action","result","error","feedback",
        ]);
        
        this.ControllerAction = this.tb.classViewer("ControllerAction", [
          "reasoning","tool_name","tool_args","additional_calls","status","is_final",
        ]);
        
        this.CriticResult = this.tb.classViewer("CriticResult", [
          "is_sufficient","explanation","suggested_approach",
        ]);
        
        this.DescribeBatchResult = this.tb.classViewer("DescribeBatchResult", [
          "summaries",
        ]);
        
        this.DescribeItemSummary = this.tb.classViewer("DescribeItemSummary", [
          "id","summary",
        ]);
        
        this.DescribeTarget = this.tb.classViewer("DescribeTarget", [
          "id","tool","tool_args","reasoning","result",
        ]);
        
        this.ExpandedRef = this.tb.classViewer("ExpandedRef", [
          "ref_id","content",
        ]);
        
        this.FewShot = this.tb.classViewer("FewShot", [
          "user","reasoning","tool","args",
        ]);
        
        this.LoopTurn = this.tb.classViewer("LoopTurn", [
          "n","reasoning","status","tool_call","additional_calls","tool_result","expansions",
        ]);
        
        this.Message = this.tb.classViewer("Message", [
          "role","content",
        ]);
        
        this.PlanResult = this.tb.classViewer("PlanResult", [
          "reasoning","plan","n_steps",
        ]);
        
        this.PriorResult = this.tb.classViewer("PriorResult", [
          "ref_id","tool","summary","expanded_in_turn",
        ]);
        
        this.ReferenceCandidate = this.tb.classViewer("ReferenceCandidate", [
          "ref_id","tool","summary","tool_args","ts_offset_s",
        ]);
        
        this.ReferenceSelection = this.tb.classViewer("ReferenceSelection", [
          "ref_id","reason",
        ]);
        
        this.ReferenceSelectorResult = this.tb.classViewer("ReferenceSelectorResult", [
          "reasoning","selected",
        ]);
        
        this.RouteOption = this.tb.classViewer("RouteOption", [
          "name","description",
        ]);
        
        this.RoutingResult = this.tb.classViewer("RoutingResult", [
          "intent","needs_tool","route","response",
        ]);
        
        this.ScreenVerdict = this.tb.classViewer("ScreenVerdict", [
          "injection_detected","reason","spans",
        ]);
        
        this.ToolCall = this.tb.classViewer("ToolCall", [
          "tool","args",
        ]);
        
        this.ToolCallRequest = this.tb.classViewer("ToolCallRequest", [
          "tool_name","tool_args",
        ]);
        
        this.ToolDescription = this.tb.classViewer("ToolDescription", [
          "name","description","args_schema",
        ]);
        
        this.ToolResult = this.tb.classViewer("ToolResult", [
          "tool","result","success","error",
        ]);
        
        
    }

    reset(): void {
        this.tb.reset();
        // TODO: This should happen in Rust. Problem is, when we construct the
        // typebuilder we instantiate class builders once and it seems to make
        // a JS copy, bypassing the Rust side? In Python however, every time we
        // access a class builder with @property, we get a new instance that
        // wraps over the Rust type builder, so we only need to call tb.reset().
        // In JS it's not possible unless we refactor the way class builders are
        // accessed.
        
    }

    __tb() {
      return this.tb._tb();
    }

    string(): FieldType {
        return this.tb.string()
    }

    literalString(value: string): FieldType {
        return this.tb.literalString(value)
    }

    literalInt(value: number): FieldType {
        return this.tb.literalInt(value)
    }

    literalBool(value: boolean): FieldType {
        return this.tb.literalBool(value)
    }

    int(): FieldType {
        return this.tb.int()
    }

    float(): FieldType {
        return this.tb.float()
    }

    bool(): FieldType {
        return this.tb.bool()
    }

    list(type: FieldType): FieldType {
        return this.tb.list(type)
    }

    null(): FieldType {
        return this.tb.null()
    }

    map(key: FieldType, value: FieldType): FieldType {
        return this.tb.map(key, value)
    }

    union(types: FieldType[]): FieldType {
        return this.tb.union(types)
    }

    addClass<Name extends string>(name: Name): ClassBuilder<Name> {
        return this.tb.addClass(name);
    }

    addEnum<Name extends string>(name: Name): EnumBuilder<Name> {
        return this.tb.addEnum(name);
    }

    addBaml(baml: string): void {
        this.tb.addBaml(baml);
    }
}