/*************************************************************************************************

Welcome to Baml! To use this generated code, please run one of the following:

$ npm install @boundaryml/baml
$ yarn add @boundaryml/baml
$ pnpm add @boundaryml/baml

*************************************************************************************************/

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ npm install @boundaryml/baml
//
/* eslint-disable */
// tslint:disable
// @ts-nocheck
// biome-ignore format: autogenerated code

import type { Image, Audio, Pdf, Video } from "@boundaryml/baml"
/**
 * Recursively partial type that can be null.
 *
 * @deprecated Use types from the `partial_types` namespace instead, which provides type-safe partial implementations
 * @template T The type to make recursively partial.
 */
export type RecursivePartialNull<T> = T extends object
    ? { [P in keyof T]?: RecursivePartialNull<T[P]> }
    : T | null;

export interface Checked<T,CheckName extends string = string> {
    value: T,
    checks: Record<CheckName, Check>,
}

export interface Check {
    name: string,
    expr: string
    status: "succeeded" | "failed"
}

export function all_succeeded<CheckName extends string>(checks: Record<CheckName, Check>): boolean {
    return get_checks(checks).every(check => check.status === "succeeded")
}

export function get_checks<CheckName extends string>(checks: Record<CheckName, Check>): Check[] {
    return Object.values(checks)
}
/**
 * A previous attempt for actor-critic retry loop
 */
export interface Attempt {
  n: number
  action: ControllerAction
  result: string
  error?: string | null
  feedback?: string | null
  
}

/**
 * Action decision returned by loop and actor controllers
 */
export interface ControllerAction {
  reasoning: string
  tool_name: string
  tool_args: string
  additional_calls?: ToolCallRequest[] | null
  status?: string | null
  is_final?: boolean | null
  
}

/**
 * Critic evaluation result
 */
export interface CriticResult {
  is_sufficient: boolean
  explanation: string
  suggested_approach?: string | null
  
}

export interface DescribeBatchResult {
  summaries: DescribeItemSummary[]
  
}

export interface DescribeItemSummary {
  id: string
  summary: string
  
}

export interface DescribeTarget {
  id: string
  tool: string
  tool_args: string
  reasoning: string
  result: string
  
}

/**
 * A ref:<id> argument that was expanded inline during a turn
 */
export interface ExpandedRef {
  ref_id: string
  content: string
  
}

/**
 * A canonical example of how the agent should pick a tool for a given user request.
 * Few-shots are domain-specific — pass at config time on a per-route basis (e.g., a
 * neo4j route ships graph-query examples; a web route ships search-formulation examples).
 */
export interface FewShot {
  user: string
  reasoning: string
  tool: string
  args: string
  
}

/**
 * A single turn in a loop-based pattern
 */
export interface LoopTurn {
  n: number
  reasoning?: string | null
  status?: string | null
  tool_call?: ToolCall | null
  additional_calls?: ToolCallRequest[] | null
  tool_result?: ToolResult | null
  expansions?: ExpandedRef[] | null
  
}

/**
 * Conversation message for history context
 */
export interface Message {
  role: string
  content: string
  
}

/**
 * Strategic plan produced by the `planner` pattern BEFORE any tool runs.
 * The planner never executes a tool — it only describes the approach, which
 * downstream loop patterns receive as their trailing `planContext` argument
 * (harness-patterns/patterns/planner.server.ts → `formatPlanContext`).
 * `LoopController` takes it as its own `plan_context` parameter (tier 2);
 * `ActorController` merges it into `context`, which is cache-safe there.
 */
export interface PlanResult {
  /**
   * Field name deliberately matches ControllerAction.reasoning — one
   * vocabulary for "why this course of action", wherever it is produced.
   */
  reasoning: string
  plan: string
  n_steps: number
  
}

/**
 * A compact reference to a tool result from a previous task/turn.
 * The LLM can pass ref:<ref_id> as a tool argument value to retrieve full data.
 */
export interface PriorResult {
  ref_id: string
  tool: string
  summary: string
  expanded_in_turn?: number | null
  
}

export interface ReferenceCandidate {
  ref_id: string
  tool: string
  summary: string
  tool_args?: string | null
  ts_offset_s: number
  
}

export interface ReferenceSelection {
  ref_id: string
  reason: string
  
}

export interface ReferenceSelectorResult {
  reasoning: string
  selected: ReferenceSelection[]
  
}

/**
 * A named route option for the router pattern
 */
export interface RouteOption {
  name: string
  description: string
  
}

/**
 * Routing decision
 */
export interface RoutingResult {
  intent: string
  needs_tool: boolean
  route?: string | null
  response?: string | null
  
}

export interface ScreenVerdict {
  injection_detected: boolean
  reason: string
  spans: string[]
  
}

/**
 * Tool call event
 */
export interface ToolCall {
  tool: string
  args: string
  
}

/**
 * One extra tool call inside a multi-call turn (ControllerAction.additional_calls).
 * Field names deliberately match ControllerAction's singular fields — one
 * vocabulary, demonstrated everywhere (see the few-shot encoding lesson in
 * simpleLoop.baml: disagreeing demonstrations are defects).
 */
export interface ToolCallRequest {
  tool_name: string
  tool_args: string
  
}

/**
 * Description of an available tool, passed to patterns at runtime
 */
export interface ToolDescription {
  name: string
  description: string
  args_schema?: string | null
  
}

/**
 * Tool execution result
 */
export interface ToolResult {
  tool: string
  result: string
  success: boolean
  error?: string | null
  
}
